### ISSUE TITLE
Error installing on Ubuntu 16.04: No instance for (MonadBase IO m)

### ISSUE THREAD

**Issue by krlmlr** [kazu-yamamoto/logger#160] opened 2018-03-22 14:27 UTC
New to Haskell. I'm seeing:

```
$ cabal install monad-logger --constraint 'monad-logger < 0.3.28.2'
Resolving dependencies...
Downloading monad-logger-0.3.28.1...
Configuring monad-logger-0.3.28.1...
Building monad-logger-0.3.28.1...
Installed monad-logger-0.3.28.1
$ cabal install monad-logger --constraint 'monad-logger < 0.3.28.3'
Resolving dependencies...
Configuring monad-logger-0.3.28.2...
Building monad-logger-0.3.28.2...
Failed to install monad-logger-0.3.28.2
Build log ( /home/mvers/.cabal/logs/monad-logger-0.3.28.2.log ):
Configuring monad-logger-0.3.28.2...
Building monad-logger-0.3.28.2...
Preprocessing library monad-logger-0.3.28.2...
[1 of 1] Compiling Control.Monad.Logger ( Control/Monad/Logger.hs, dist/build/Control/Monad/Logger.o )

Control/Monad/Logger.hs:362:99:
    No instance for (MonadBase IO m)
      arising from the 'deriving' clause of a data type declaration
    Possible fix:
      use a standalone 'deriving instance' declaration,
        so you can specify the instance context yourself
    When deriving the instance for (MonadResource (NoLoggingT m))
cabal: Error: some packages failed to install:
monad-logger-0.3.28.2 failed during the building phase. The exception was:
ExitFailure 1
```

Do you need more input?

**Comment by phadej** [comment] 2018-03-23 06:04
This is reproducible with GHC-7.10.3 and older

**Comment by phadej** [comment] 2018-03-23 06:07
I suspect this is due changes in `resourcet-1.2.0`

**Comment by mrkkrp** [comment] 2018-03-23 07:47
Apparently this will force everybody to drop support for GHC 7.10 and older now. E.g. I have: https://travis-ci.org/mrkkrp/slug/builds/357268657.

**Comment by phadej** [comment] 2018-03-23 08:59
As a Hackage Trustee I'm tempted to make a revision which simply bump `base` lower bound for that version. The patch fixing issue seems to be relatively simple, hopefully it will be merged and released soon.

https://hackage.haskell.org/package/monad-logger-0.3.28.2/revisions/

**Closed** 2018-03-24 18:02 UTC

**Comment by snoyberg** [comment] 2018-03-24 18:04
@krlmlr Can you clarify which version of GHC you are using?

**Comment by krlmlr** [comment] 2018-07-14 22:09
Sorry, can't recollect.
